# Generated by Django 4.0.5 on 2022-12-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0003_alter_session_year_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
