# Generated by Django 4.1.4 on 2023-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0004_leavereportstudent_leavereportstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
