# Generated by Django 4.0.5 on 2022-12-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0005_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='stauts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
