# Generated by Django 4.0.3 on 2023-01-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0008_alter_attendance_session_year_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('session_year', models.ForeignKey(default='Free', null=True, on_delete=django.db.models.deletion.CASCADE, to='AMS.session_year')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS.staff')),
            ],
        ),
    ]
