# Generated by Django 4.1.4 on 2023-02-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0008_alter_attendance_session_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
    ]
