# Generated by Django 4.1.4 on 2023-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0011_attendance_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
