# Generated by Django 4.1.4 on 2023-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0012_course_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='stauts',
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='absent',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='present',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
