# Generated by Django 4.1.4 on 2023-03-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0013_remove_attendance_report_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='present',
        ),
    ]
