# Generated by Django 4.1.4 on 2023-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0014_remove_attendance_report_absent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='staff_username',
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='attendance_status',
            field=models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('L', 'Late')], default=True, max_length=1),
            preserve_default=False,
        ),
    ]
