# Generated by Django 4.1.4 on 2023-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0015_remove_attendance_staff_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
